### ISSUE TITLE
Spotify Register Problem

### ISSUE THREAD

**Issue by rdemianchuk** [mental32/spotify.py#43] opened 2019-12-01 19:48 UTC
Hi, @mental32  ! thanks for the fantastic work, your library is beautiful, I am using it to the fullest extent in my project)
However, there is a problem in registering the Spotify client
Calling the following code:

spotify.User.from_code (
             code = code,
             client = spotify_cl,
             redirect_uri = self.redirect_uri,
)
I came across the following problem in the __init__ method of the User class: /spotify/models/user.py, 88 line of code
self.url = data.poprecently ("external_urls"). get ("spotify", None)
-> AttributeError: 'dict' object has no attribute 'poprecently'

If you comment out this line, then everything is in order and everything works, please correct this moment.
Sincerely, Roman Demyanchuk!

**Comment by mental32** [comment] 2019-12-01 20:16
@HALLOWe3n Nice to hear you're enjoying the library :)

I can't reproduce this issue, and the source agrees with me, `data.poprecently` is not part of the checked in code.

What version of the library did you install?
Did you install the library from pypi or github?

**Comment by rdemianchuk** [comment] 2019-12-01 20:51
@mental32 
I downloaded the library from pypi, and there were problems in getting the tokens in the documentation.
I think it's worth pumping a library from Github, how best to do this?

**Comment by mental32** [comment] 2019-12-01 20:57
@HALLOWe3n 
I just tested a pypi release `0.8.2` and it looks fine, perhaps try reinstalling it?
If not you can always install it through git `pip install git+https://github.com/mental32/spotify.py#egg=spotify`

**Comment by rdemianchuk** [comment] 2019-12-01 20:59
@mental32 
I just tested the git version, everything is just fine!
Thanks for the great work, you make life and coding better! :)

**Closed as completed** 2019-12-01 21:00 UTC
